default: &default
  adapter: postgresql
  encoding: unicode
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  database: <%= ENV['POSTGRES_DB'] %>
  host: db

development:
  <<: *default
  database: my_todo_app_development

test:
  <<: *default
  database: my_todo_app_test

production:
  <<: *default
  database: my_todo_app_production
  username: my_todo_app
  password: <%= ENV["MY_TODO_APP_DATABASE_PASSWORD"] %>
