default: &default
  adapter: postgresql
  encoding: unicode
  host: db #<= 追加
  username: postgres #<= 追加
  password: password #<= 追加
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: my_todo_app_development

test:
  <<: *default
  database: my_todo_app_test

production:
  <<: *default
  database: my_todo_app_production
  username: my_todo_app
  password: <%= ENV["MY_TODO_APP_DATABASE_PASSWORD"] %>
